FIX: fetched page file name to reflect file type ...
... so that lesspipe can do
its job

diff --git a/bin/wless b/bin/wless
--- a/bin/wless
+++ b/bin/wless
@@ -1,12 +1,22 @@
 #!/bin/sh
 # wless - web page less
 # found in: http://chneukirchen.org/dotfiles/bin/wless
-# TODO:
-#  - FIX: fetched page file name to reflect file type so that lesspipe can do its job, e.g. 
-#         wless https://papers.mathyvanhoef.com/ccs2017.pdf
-#         will not treat file as PDF and view it properly (i.e. use pdftotext)
 export LESSOPEN='|/usr/bin/lesspipe %s'
-TEMPFILE=$(mktemp)
-trap "rm -f $TEMPFILE" INT TERM EXIT
-curl -L "$@" -o $TEMPFILE
-less $TEMPFILE
+TEMPDIR=$(mktemp -d)
+trap "rm -rf $TEMPDIR" INT TERM EXIT
+cd $TEMPDIR
+FILENAME="${@##*/}"
+FILENAME="${FILENAME:-"unset"}"
+# echo "FILENAME=${FILENAME}" |od -c
+curl -4 -L "$@" -D headers.txt -o $FILENAME
+if [ $? -ne 0 ]
+then
+	>&2 echo "ERROR: curl failed ... EXITING"
+	exit 1
+fi
+EXTENSION="$(sed -n '/^Content-Type:/ s|Content-Type: *[^/]*/\([a-z0-9A-Z]\+\).*$|\1|p' headers.txt|tail -1)"
+# echo "EXTENSION=${EXTENSION}" | od -c
+# echo "mv $FILENAME $FILENAME.$EXTENSION"
+mv $FILENAME $FILENAME.$EXTENSION
+# ls $TEMPDIR | od -c
+less $FILENAME.$EXTENSION
